name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: login to docker hub
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          docker login -u $username -p $password


      - name: Build Docker Image
        run: docker build -t ganesh20101/hello-cloud-engine-labs:${{ github.sha }} .

      - name: Push Docker Image to Docker Hub
        run: docker push ganesh20101/hello-cloud-engine-labs:${{ github.sha }}
